canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

baseurl = "https://kalispera.netlify.com/"
disqusShortname = "kalispera"
languageCode = "en-us"
paginate = 7

title = "Kalispera"
author = "Aky"

[params]
backtotopstr = "Back to top"
bio = "Runner -  Artist-  Writer- Nature & Coffee lover"
comments = "disqus"
copyright = "[theme](https://github.com/digitalcraftsman/hugo-steam-theme) | [hugo](https://gohugo.io/) | [netlify](https://www.netlify.com/)"
description = "Blog about science, art, technology, issues, and society"
github = "akufta"
googleanalytics = ""
instagram = "akufta.art/"
keepreadingstr = "Keep reading"
location = "US"
name = "Aky"
pagenotfoundtitle = "404 - Page not found"
sharestr = "Share"
subtitle = " A blog about science, art, and society."
twitter = "akufta"
