SectionPagesMenu = "main"
baseurl = "https://kalispera.netlify.com"
disqusShortname = "art-res-tumblr-com"
enableRobotsTXT = true
footnoteReturnLinkContents = "â†©"
googleAnalytics = "UA-47550631-5"
languageCode = "en-US"
paginate = 10
theme = "after-dark"
title = "Kalispera"
description = "An exploration of the intersection between art and science"

[blackfriday]
fractions = false
hrefTargetBlank = true

[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Portfolio"
    url = "https://www.behance.net/allisonkufta"
    weight = 2

[[menu.main]]
    name = "Photography"
    url = "https://500px.com/akufta"
    weight = 3
[[menu.main]]
    name = "Shop"
    url = "https://inktale.com/akufta"
    weight = 4

[[menu.main]]
    name = "Reading List"
    url = "https://www.goodreads.com/user/show/31960024-allison-kufta"
    weight = 5


[params]
author = "Aky"
description = "A blog about science, art, and society. "
hide_author = false
images = ["https://source.unsplash.com/collection/1234708/2000x1322"]
powered_by = true
show_menu = true
theme_variant = "standard"
[params.seo.webmaster_verifications]   
google = ""