baseurl = "https://kalispera.netlify.com/"
disqusShortname = "kalispera"
languageCode = "en-us"
paginate = 7
theme = "hugo-steam-theme"
title = "Kalispera"
[params]
backtotopstr = "Back to top"
bio = "Runner -  Artist-  Writer- Nature & Coffee lover"
comments = "disqus"
copyright = "[theme](https://github.com/digitalcraftsman/hugo-steam-theme) | [hugo](https://gohugo.io/) | [netlify](https://www.netlify.com/)"
description = "Blog about science, art, technology, issues, and society"
github = ""
googleanalytics = ""
instagram = ""
keepreadingstr = "Keep reading"
location = "US"
name = "Aky"
pagenotfoundtitle = "404 - Page not found"
sharestr = "Share"
subtitle = " A blog about science, art, and society."
themecolor = "blue"
title = "Kalispera"
twitter = ""
[taxonomies]
tag = "tags"
<<<<<<< HEAD

[params]

	title = "Kalispera"
	subtitle = " A blog about science, art, and society."
	copyright = "[theme](https://github.com/digitalcraftsman/hugo-steam-theme) | [hugo](https://gohugo.io/) | [netlify](https://www.netlify.com/)"

	# You can choose between green, orange, red and blue.
	themeColor = "blue"
	# Enable Google Analytics be inserting your tracking code
	googleAnalytics = ""

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Aky"
	bio = "Runner -  Artist-  Writer- Nature & Coffee lover"
	description = "Blog about science, art, technology, issues, and society"
	location = "US"
	twitter = ""
	github = ""
	instagram = "astrikos.art"

	# Enable a comment system
	# You can choose between Disqus or Google Plus by setting comments
	# to disqus or googleplus. For using Disqus you need to enter your
	# shortname in disqusShortname at the top of the configs. 
	comments = "disqus"

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"

	
=======
>>>>>>> ad93534e89139f1e6acc05df1abcf80e4f74bfa7
